[workspace]
resolver = "2"
members = ["protocol", "doord", "door-theme", "door-greeter", "door-settings"]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/satorisage/door"

[workspace.dependencies]
protocol = { path = "protocol" }
door-theme = { path = "door-theme" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
zeroize = { version = "1", features = ["derive"] }
libc = "0.2"
pam-client = "0.5"
